/**
 * Tokyo Night theme definition.
 *
 * https://github.com/enkia/tokyo-night-vscode-theme
 *
 * Tokyo Night: deep blue/purple dark theme
 * Tokyo Night Storm: lighter, muted variant
 */

import type { ThemeDefinition } from "./types";

const nightPalette = {
    bg: { name: "bg", hex: "#1a1b26", description: "Background" },
    bgDark: { name: "bg-dark", hex: "#16161e", description: "Darker background" },
    fg: { name: "fg", hex: "#c0caf5", description: "Foreground" },
    fgDark: { name: "fg-dark", hex: "#a9b1d6", description: "Muted foreground" },
    blue: { name: "blue", hex: "#7aa2f7", description: "Blue" },
    purple: { name: "purple", hex: "#bb9af7", description: "Purple" },
    red: { name: "red", hex: "#f7768e", description: "Red" },
    orange: { name: "orange", hex: "#ff9e64", description: "Orange" },
    yellow: { name: "yellow", hex: "#e0af68", description: "Yellow" },
    green: { name: "green", hex: "#73daca", description: "Green" },
    cyan: { name: "cyan", hex: "#7dcfff", description: "Cyan" },
    border: { name: "border", hex: "#24283b", description: "Border" },
    surface: { name: "surface", hex: "#24283b", description: "Surface" },
    surfaceHighlight: { name: "surface-highlight", hex: "#414868", description: "Surface highlight" },
} as const;

const stormPalette = {
    bg: { name: "bg", hex: "#24283b", description: "Background" },
    bgDark: { name: "bg-dark", hex: "#1f2335", description: "Darker background" },
    fg: { name: "fg", hex: "#c0caf5", description: "Foreground" },
    fgDark: { name: "fg-dark", hex: "#a9b1d6", description: "Muted foreground" },
    blue: { name: "blue", hex: "#7aa2f7", description: "Blue" },
    purple: { name: "purple", hex: "#bb9af7", description: "Purple" },
    red: { name: "red", hex: "#f7768e", description: "Red" },
    orange: { name: "orange", hex: "#ff9e64", description: "Orange" },
    yellow: { name: "yellow", hex: "#e0af68", description: "Yellow" },
    green: { name: "green", hex: "#73daca", description: "Green" },
    cyan: { name: "cyan", hex: "#7dcfff", description: "Cyan" },
    border: { name: "border", hex: "#2e3c64", description: "Border" },
    surface: { name: "surface", hex: "#2e3c64", description: "Surface" },
    surfaceHighlight: { name: "surface-highlight", hex: "#565f89", description: "Surface highlight" },
} as const;

const lightPalette = {
    bg: { name: "bg", hex: "#e1e2e7", description: "Background" },
    bgDark: { name: "bg-dark", hex: "#d5d6db", description: "Darker background" },
    fg: { name: "fg", hex: "#343b58", description: "Foreground" },
    fgDark: { name: "fg-dark", hex: "#565f89", description: "Muted foreground" },
    blue: { name: "blue", hex: "#2e7de9", description: "Blue" },
    purple: { name: "purple", hex: "#7847bd", description: "Purple" },
    red: { name: "red", hex: "#f52a65", description: "Red" },
    orange: { name: "orange", hex: "#b15c00", description: "Orange" },
    yellow: { name: "yellow", hex: "#8f5e14", description: "Yellow" },
    green: { name: "green", hex: "#587539", description: "Green" },
    cyan: { name: "cyan", hex: "#007197", description: "Cyan" },
    border: { name: "border", hex: "#c6c7d1", description: "Border" },
    surface: { name: "surface", hex: "#c6c7d1", description: "Surface" },
    surfaceHighlight: { name: "surface-highlight", hex: "#a8a9b8", description: "Surface highlight" },
} as const;

export const tokyoNight: ThemeDefinition = {
    id: "tokyo-night",
    displayName: "Tokyo Night",
    description: "Dark blue/purple theme",
    defaultVariant: "tokyo-night",
    variants: [
        {
            id: "tokyo-night",
            name: "Tokyo Night",
            isDark: true,
            palette: nightPalette,
            tokens: {
                background: nightPalette.bg.hex,
                foreground: nightPalette.fg.hex,
                card: nightPalette.bgDark.hex,
                "card-foreground": nightPalette.fg.hex,
                popover: nightPalette.bgDark.hex,
                "popover-foreground": nightPalette.fg.hex,
                primary: nightPalette.blue.hex,
                "primary-foreground": nightPalette.bg.hex,
                secondary: nightPalette.surface.hex,
                "secondary-foreground": nightPalette.fg.hex,
                muted: nightPalette.surface.hex,
                "muted-foreground": nightPalette.fgDark.hex,
                accent: nightPalette.purple.hex,
                "accent-foreground": nightPalette.bg.hex,
                destructive: nightPalette.red.hex,
                "destructive-foreground": nightPalette.fg.hex,
                border: nightPalette.border.hex,
                input: nightPalette.border.hex,
                ring: nightPalette.blue.hex,
                radius: "0.5rem",
            },
        },
        {
            id: "tokyo-night-storm",
            name: "Tokyo Night Storm",
            isDark: true,
            palette: stormPalette,
            tokens: {
                background: stormPalette.bg.hex,
                foreground: stormPalette.fg.hex,
                card: stormPalette.bgDark.hex,
                "card-foreground": stormPalette.fg.hex,
                popover: stormPalette.bgDark.hex,
                "popover-foreground": stormPalette.fg.hex,
                primary: stormPalette.blue.hex,
                "primary-foreground": stormPalette.bg.hex,
                secondary: stormPalette.surface.hex,
                "secondary-foreground": stormPalette.fg.hex,
                muted: stormPalette.surface.hex,
                "muted-foreground": stormPalette.fgDark.hex,
                accent: stormPalette.purple.hex,
                "accent-foreground": stormPalette.bg.hex,
                destructive: stormPalette.red.hex,
                "destructive-foreground": stormPalette.fg.hex,
                border: stormPalette.border.hex,
                input: stormPalette.border.hex,
                ring: stormPalette.blue.hex,
                radius: "0.5rem",
            },
        },
        {
            id: "tokyo-night-light",
            name: "Tokyo Night Light",
            isDark: false,
            palette: lightPalette,
            tokens: {
                background: lightPalette.bg.hex,
                foreground: lightPalette.fg.hex,
                card: lightPalette.bgDark.hex,
                "card-foreground": lightPalette.fg.hex,
                popover: lightPalette.bgDark.hex,
                "popover-foreground": lightPalette.fg.hex,
                primary: lightPalette.blue.hex,
                "primary-foreground": lightPalette.bg.hex,
                secondary: lightPalette.surface.hex,
                "secondary-foreground": lightPalette.fg.hex,
                muted: lightPalette.surface.hex,
                "muted-foreground": lightPalette.fgDark.hex,
                accent: lightPalette.purple.hex,
                "accent-foreground": lightPalette.bg.hex,
                destructive: lightPalette.red.hex,
                "destructive-foreground": lightPalette.fg.hex,
                border: lightPalette.border.hex,
                input: lightPalette.border.hex,
                ring: lightPalette.blue.hex,
                radius: "0.5rem",
            },
        },
    ],
};
